Adds a boolean to switch between global and player item recommendations
jwplayer/jwplayer-ios-bestPracticeApps pull request #83
Opened 2022-01-31 22:01 UTC by david-almaguer

Adds a boolean to switch between global and player item recommendations

2022-01-31 22:12 UTC, DavidPerezP124 approved these changes

2022-02-01 16:33 UTC, s-seibert requested changes

2022-02-01 16:33 UTC, s-seibert commented on JWBestPracticeApps/Recommendations/Recommendations/ViewController.swift
> +            if useRecPerPlayerItem {
To make this more clear, why not combine this if statement with the one on line 62? This way the logic is in one place for where to put the recommendations url.

2022-02-01 19:03 UTC, DavidPerezP124 approved these changes

2022-02-01 19:57 UTC, s-seibert approved these changes

2022-02-01 19:58 UTC, merged