[SDK-9699] Add basic player BPA
jwplayer/jwplayer-ios-bestPracticeApps pull request #95
Opened 2022-06-09 21:29 UTC by david-almaguer

Adds a basic player implementation using JWPlayerTVKit tvOS SDK 4.x.x.
- Global README.md is updated.
- Added new groups to separate iOS targets from tvOS targets.
- Added new BasicTVPlayer target

2022-10-19 22:23 UTC, DavidPerezP124 commented on JWBestPracticeApps/Podfile
> +    pod 'JWPlayerTVKit', '~> 1'
It seems we need to specify the platform for tvOS as well. We can let the `pod install` script decide it automatically by removing the first line but it throws a few warnings for this.

2022-10-21 17:15 UTC, DavidPerezP124 approved these changes

2022-10-21 17:26 UTC, s-seibert requested changes

2022-10-21 17:26 UTC, s-seibert commented on README.md
> +This repository contains samples relating to the JWPlayerKit SDK version 4.x for iOS and JWPlayerTVKit SDK version 4.x for tvOS.
Shouldn't this say 1.x for tvOS?

2022-10-21 17:29 UTC, david-almaguer commented on README.md
> +This repository contains samples relating to the JWPlayerKit SDK version 4.x for iOS and JWPlayerTVKit SDK version 4.x for tvOS.
Addressed

2022-10-21 18:31 UTC, s-seibert approved these changes

2022-10-21 18:47 UTC, Tozarf approved these changes
LGTM 💯

2022-10-21 19:07 UTC, merged